export type StopType =
  | 'nature'
  | 'food'
  | 'kitsch'
  | 'art'
  | 'history'
  | 'scenic'
  | 'activity'
  | 'rest';

export type TripStop = {
  // Identity
  id: string;
  name: string;
  subtitle: string;
  latitude: number;
  longitude: number;
  type: StopType;
  arrivalRadiusMeters: number;
  revealEmoji: string;

  // Reveal content
  hook: string;
  whatToDo: string[];
  proTips: string[];
  context: string;

  // Practical strip
  estimatedDurationMinutes: number;
  suggestedDuration: string;
  costNote: string;
  hoursToday: string;

  // Conditional (show only when present)
  whatToOrder?: string | null;
  photoTips?: string | null;
  parkingNotes?: string | null;
  safetyNotes?: string | null;
};

export type TripDay = {
  id: string;
  label: string;
  stops: TripStop[];
};

export type TripFamily = {
  id: string;
  name: string;
  days: TripDay[];
};

export const TRIPS: {families: TripFamily[]} = {
  families: [
    {
      id: 'fords',
      name: 'The Fords',
      days: [
        {
          id: 'fords-day1',
          label: 'Nashville → St. Louis',
          stops: [
            {
              id: 'fords-day1-stop1',
              name: 'TBD Ford Stop 1',
              subtitle: 'TBD',
              revealEmoji: '📍',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 36.1627,
              longitude: -86.7816,
              type: 'scenic',
              estimatedDurationMinutes: 20,
              arrivalRadiusMeters: 200,
              suggestedDuration: '20 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
          ],
        },
      ],
    },
    {
      id: 'billings',
      name: 'The Billings',
      days: [
        {
          id: 'billings-day0',
          label: 'Hyrum → Kemmerer (Night Drive)',
          stops: [
            {
              id: 'billings-day0-stop1',
              name: 'Kemmerer Overnight Arrival',
              subtitle: 'TBD',
              revealEmoji: '🌙',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 41.7916,
              longitude: -110.5377,
              type: 'rest',
              estimatedDurationMinutes: 30,
              arrivalRadiusMeters: 220,
              suggestedDuration: '30 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
          ],
        },
        {
          id: 'billings-day1',
          label: 'Kemmerer → Cody',
          stops: [
            {
              id: 'billings-day1-stop1',
              name: 'J.C. Penney Mother Store',
              subtitle: 'TBD',
              revealEmoji: '🏪',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 41.7924,
              longitude: -110.5368,
              type: 'history',
              estimatedDurationMinutes: 20,
              arrivalRadiusMeters: 200,
              suggestedDuration: '20 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
            {
              id: 'billings-day1-stop2',
              name: 'J.C. Penney Statue',
              subtitle: 'TBD',
              revealEmoji: '🗿',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 41.792,
              longitude: -110.5375,
              type: 'kitsch',
              estimatedDurationMinutes: 2,
              arrivalRadiusMeters: 160,
              suggestedDuration: '2 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
            {
              id: 'billings-day1-stop3',
              name: 'Farson Mercantile (Big Cone)',
              subtitle: 'TBD',
              revealEmoji: '🍦',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 42.1109,
              longitude: -109.442,
              type: 'food',
              estimatedDurationMinutes: 25,
              arrivalRadiusMeters: 220,
              suggestedDuration: '25 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
            {
              id: 'billings-day1-stop4',
              name: 'Maven Optics',
              subtitle: 'TBD',
              revealEmoji: '🔭',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 42.833,
              longitude: -108.731,
              type: 'activity',
              estimatedDurationMinutes: 60,
              arrivalRadiusMeters: 180,
              suggestedDuration: '60 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
            {
              id: 'billings-day1-stop5',
              name: 'Lander Bar & Coalter Block',
              subtitle: 'TBD',
              revealEmoji: '🍺',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 42.8329,
              longitude: -108.7306,
              type: 'food',
              estimatedDurationMinutes: 45,
              arrivalRadiusMeters: 180,
              suggestedDuration: '45 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
            {
              id: 'billings-day1-stop6',
              name: 'Sinks Canyon State Park',
              subtitle: 'TBD',
              revealEmoji: '🌊',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 42.7472,
              longitude: -108.8264,
              type: 'nature',
              estimatedDurationMinutes: 30,
              arrivalRadiusMeters: 240,
              suggestedDuration: '30 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
            {
              id: 'billings-day1-stop7',
              name: 'Wind River Canyon Scenic Drive',
              subtitle: 'TBD',
              revealEmoji: '🏔️',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 43.55,
              longitude: -108.19,
              type: 'scenic',
              estimatedDurationMinutes: 40,
              arrivalRadiusMeters: 320,
              suggestedDuration: '40 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
            {
              id: 'billings-day1-stop8',
              name: 'Hot Springs State Park',
              subtitle: 'TBD',
              revealEmoji: '♨️',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 43.6464,
              longitude: -108.2055,
              type: 'nature',
              estimatedDurationMinutes: 30,
              arrivalRadiusMeters: 220,
              suggestedDuration: '30 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
            {
              id: 'billings-day1-stop9',
              name: 'Irma Hotel',
              subtitle: 'TBD',
              revealEmoji: '🏨',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 44.5241,
              longitude: -109.056,
              type: 'history',
              estimatedDurationMinutes: 75,
              arrivalRadiusMeters: 180,
              suggestedDuration: '75 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
          ],
        },
        {
          id: 'billings-day2',
          label: 'Cody Museums + Wapiti Valley',
          stops: [
            {
              id: 'billings-day2-stop1',
              name: 'Heart Mountain WWII Interpretive Center',
              subtitle: 'TBD',
              revealEmoji: '🕊️',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 44.67,
              longitude: -108.94,
              type: 'history',
              estimatedDurationMinutes: 120,
              arrivalRadiusMeters: 220,
              suggestedDuration: '120 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
            {
              id: 'billings-day2-stop2',
              name: 'Cody Dug Up Gun Museum',
              subtitle: 'TBD',
              revealEmoji: '🔫',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 44.5244,
              longitude: -109.064,
              type: 'history',
              estimatedDurationMinutes: 40,
              arrivalRadiusMeters: 180,
              suggestedDuration: '40 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
            {
              id: 'billings-day2-stop3',
              name: 'Buffalo Bill Dam',
              subtitle: 'TBD',
              revealEmoji: '🌊',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 44.4975,
              longitude: -109.1813,
              type: 'scenic',
              estimatedDurationMinutes: 20,
              arrivalRadiusMeters: 220,
              suggestedDuration: '20 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
            {
              id: 'billings-day2-stop4',
              name: 'Smith Mansion',
              subtitle: 'TBD',
              revealEmoji: '🏚️',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 44.4878,
              longitude: -109.48,
              type: 'kitsch',
              estimatedDurationMinutes: 10,
              arrivalRadiusMeters: 220,
              suggestedDuration: '10 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
            {
              id: 'billings-day2-stop5',
              name: 'Lonely Big Boy Statue',
              subtitle: 'TBD',
              revealEmoji: '🗿',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 44.49,
              longitude: -109.42,
              type: 'kitsch',
              estimatedDurationMinutes: 2,
              arrivalRadiusMeters: 180,
              suggestedDuration: '2 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
            {
              id: 'billings-day2-stop6',
              name: 'Buffalo Bill Center of the West',
              subtitle: 'TBD',
              revealEmoji: '🎨',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 44.5258,
              longitude: -109.0714,
              type: 'art',
              estimatedDurationMinutes: 180,
              arrivalRadiusMeters: 200,
              suggestedDuration: '180 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
          ],
        },
        {
          id: 'billings-day3',
          label: 'Cody Day 2 — Flex Day',
          stops: [
            {
              id: 'billings-day3-stop1',
              name: 'Buffalo Bill Center of the West (continued)',
              subtitle: 'TBD',
              revealEmoji: '🎨',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 44.5258,
              longitude: -109.0714,
              type: 'art',
              estimatedDurationMinutes: 120,
              arrivalRadiusMeters: 200,
              suggestedDuration: '120 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
            {
              id: 'billings-day3-stop2',
              name: 'Meeteetse Museums Complex',
              subtitle: 'TBD',
              revealEmoji: '🏛️',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 44.157,
              longitude: -108.866,
              type: 'history',
              estimatedDurationMinutes: 45,
              arrivalRadiusMeters: 220,
              suggestedDuration: '45 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
            {
              id: 'billings-day3-stop3',
              name: 'Legend Rock Petroglyph Site',
              subtitle: 'TBD',
              revealEmoji: '🪨',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 43.82,
              longitude: -108.62,
              type: 'history',
              estimatedDurationMinutes: 60,
              arrivalRadiusMeters: 260,
              suggestedDuration: '60 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
            {
              id: 'billings-day3-stop4',
              name: 'Wyoming Dinosaur Center',
              subtitle: 'TBD',
              revealEmoji: '🦕',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 43.6515,
              longitude: -108.1858,
              type: 'activity',
              estimatedDurationMinutes: 90,
              arrivalRadiusMeters: 220,
              suggestedDuration: '90 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
          ],
        },
        {
          id: 'billings-day4',
          label: 'Cody → Hyrum (Return)',
          stops: [
            {
              id: 'billings-day4-stop1',
              name: 'National Museum of Military Vehicles',
              subtitle: 'TBD',
              revealEmoji: '🪖',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 43.536,
              longitude: -109.57,
              type: 'history',
              estimatedDurationMinutes: 150,
              arrivalRadiusMeters: 220,
              suggestedDuration: '150 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
            {
              id: 'billings-day4-stop2',
              name: 'Dubois Jackalope Stop',
              subtitle: 'TBD',
              revealEmoji: '🐰',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 43.5325,
              longitude: -109.628,
              type: 'kitsch',
              estimatedDurationMinutes: 10,
              arrivalRadiusMeters: 200,
              suggestedDuration: '10 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
            {
              id: 'billings-day4-stop3',
              name: 'National Bighorn Sheep Center',
              subtitle: 'TBD',
              revealEmoji: '🐏',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 43.534,
              longitude: -109.631,
              type: 'nature',
              estimatedDurationMinutes: 30,
              arrivalRadiusMeters: 200,
              suggestedDuration: '30 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
            {
              id: 'billings-day4-stop4',
              name: 'Fossil Butte National Monument',
              subtitle: 'TBD',
              revealEmoji: '🦴',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 41.858,
              longitude: -110.766,
              type: 'nature',
              estimatedDurationMinutes: 45,
              arrivalRadiusMeters: 230,
              suggestedDuration: '45 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
          ],
        },
      ],
    },
    {
      id: 'halls',
      name: 'The Halls',
      days: [
        {
          id: 'halls-test',
          label: 'Test Route — Drive Home',
          stops: [
            {
              id: 'halls-test-stop1',
              name: 'Home Sweet Home',
              subtitle: 'The final destination',
              revealEmoji: '🏠',
              hook: 'You made it. The reveal system works.',
              whatToDo: [
                'Check that the animation played in sequence.',
                'Try switching between tabs.',
                'Tap "Finish Trip" and verify the completion screen.',
              ],
              proTips: [
                'If you tapped during the animation, it should have snapped to complete.',
                'Try killing the app and relaunching to test resume.',
              ],
              context:
                'This is a test stop for verifying the full reveal flow before the Billings beta.',
              latitude: 40.2551,
              longitude: -111.631,
              type: 'rest',
              estimatedDurationMinutes: 5,
              arrivalRadiusMeters: 250,
              suggestedDuration: '5 min',
              costNote: 'Free',
              hoursToday: 'Always open',
              parkingNotes: 'Your driveway.',
            },
          ],
        },
        {
          id: 'halls-day1',
          label: 'Day 1: Provo → ???',
          stops: [
            {
              id: 'halls-day1-stop1',
              name: 'TBD Halls Stop 1',
              subtitle: 'TBD',
              revealEmoji: '📍',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 40.2338,
              longitude: -111.6585,
              type: 'activity',
              estimatedDurationMinutes: 25,
              arrivalRadiusMeters: 200,
              suggestedDuration: '25 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
          ],
        },
      ],
    },
  ],
};
