export type StopType =
  | 'nature'
  | 'food'
  | 'kitsch'
  | 'art'
  | 'history'
  | 'scenic'
  | 'activity'
  | 'rest';

export type TripStop = {
  // Identity
  id: string;
  name: string;
  subtitle: string;
  latitude: number;
  longitude: number;
  type: StopType;
  arrivalRadiusMeters: number;
  revealEmoji: string;

  // Reveal content
  hook: string;
  whatToDo: string[];
  proTips: string[];
  context: string;

  // Practical strip
  estimatedDurationMinutes: number;
  suggestedDuration: string;
  costNote: string;
  hoursToday: string;

  // Conditional (show only when present)
  whatToOrder?: string | null;
  photoTips?: string | null;
  parkingNotes?: string | null;
  safetyNotes?: string | null;
};

export type TripDay = {
  id: string;
  label: string;
  stops: TripStop[];
};

export type TripFamily = {
  id: string;
  name: string;
  days: TripDay[];
};

export const TRIPS: {families: TripFamily[]} = {
  families: [
    {
      id: 'fords',
      name: 'The Fords',
      days: [
        {
          id: 'fords-day1',
          label: 'Nashville → St. Louis',
          stops: [
            {
              id: 'fords-day1-stop1',
              name: 'TBD Ford Stop 1',
              subtitle: 'TBD',
              revealEmoji: '📍',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 36.1627,
              longitude: -86.7816,
              type: 'scenic',
              estimatedDurationMinutes: 20,
              arrivalRadiusMeters: 200,
              suggestedDuration: '20 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
          ],
        },
      ],
    },
    {
      id: 'billings',
      name: 'The Billings',
      days: [
          {
                    'id': 'billings-day1',
                    'label': 'Kemmerer → Cody',
                    'stops': [
                              {
                                        'id': 'farson-mercantile',
                                        'name': 'Farson Mercantile',
                                        'subtitle': 'Home of the Big Cone',
                                        'revealEmoji': '🍦',
                                        'hook': "A gas station in the middle of nowhere Wyoming that serves ice cream scoops the size of your head. The 'baby' cone is bigger than most places' large.",
                                        'whatToDo': [
                                                  'Walk in and head to the ice cream counter in the back',
                                                  "Order the 'baby' size — trust us, the regular is absurd",
                                                  'Huckleberry and maple walnut are the local favorites',
                                                  'Browse the gift shop for Wyoming honey and apparel while you eat',
                                        ],
                                        'proTips': [
                                                  'The half-scoop is still enough for two people to share',
                                                  'They also make deli subs and pizza if you need real food',
                                                  "The building has been here since 1908 — it's survived as a boarding house, post office, hotel, and grocery store",
                                        ],
                                        'context': 'Farson is a crossroads town of about 300 people where Highway 191 meets Highway 28 in the high desert of southwestern Wyoming. The Mercantile has been the only reason to stop here for over a century. Travelers headed to Yellowstone, the Wind Rivers, and Jackson have been pulling over for ice cream since long before the interstate era.',
                                        'latitude': 42.1109,
                                        'longitude': -109.442,
                                        'type': 'food',
                                        'estimatedDurationMinutes': 25,
                                        'arrivalRadiusMeters': 220,
                                        'suggestedDuration': '20–25 min',
                                        'costNote': '~$5–8 per cone',
                                        'hoursToday': '9:00 AM – 9:00 PM',
                                        'whatToOrder': 'Baby cone. Huckleberry or maple walnut.',
                                        'photoTips': "The 'Home of the Big Cone' sign out front. Hold your cone next to your face for scale — you'll want the photo.",
                                        'parkingNotes': 'Lot right in front. Easy.',
                              },
                              {
                                        'id': 'maven-optics',
                                        'name': 'Maven Optics',
                                        'subtitle': 'Built in Lander',
                                        'revealEmoji': '🔭',
                                        'hook': 'A premium optics company that builds everything right here in this small Wyoming town. This is where the binoculars and scopes are designed, tested, and shipped.',
                                        'whatToDo': [
                                                  'Head inside and browse the full product line — binoculars, spotting scopes, rifle scopes, sunglasses',
                                                  "Ask about custom builds if you're in the market",
                                                  "Check out what's on clearance or what they might have available that's not on the website",
                                        ],
                                        'proTips': [
                                                  'Perfect 5.0 rating on Google with 170 reviews — customers rave about their quality-to-price ratio',
                                                  "If you're buying, this is the source — no middleman markup",
                                                  "Maven doesn't dilute with mass retail. Everything ships from this building.",
                                        ],
                                        'context': 'Maven was founded in Lander in 2014 by passionate hunters and outdoors enthusiasts who wanted to build high-end optics without the legacy brand markup. The company runs direct-to-consumer, designing and customizing from this location at the foot of the Wind River Range.',
                                        'latitude': 42.838,
                                        'longitude': -108.7167,
                                        'type': 'activity',
                                        'estimatedDurationMinutes': 60,
                                        'arrivalRadiusMeters': 220,
                                        'suggestedDuration': '30–60 min',
                                        'costNote': 'Free to browse',
                                        'hoursToday': '8:00 AM – 5:00 PM',
                                        'parkingNotes': 'Lot at the building.',
                              },
                              {
                                        'id': 'lander-bar-coalter-block',
                                        'name': 'Lander Bar & Coalter Block',
                                        'subtitle': 'Saloon Since 1907',
                                        'revealEmoji': '🍺',
                                        'hook': 'A bar that opened as a saloon in 1907, spent time as a hotel and a brothel, and is now the beating heart of one of the best outdoor towns in America. The tin ceilings are original. The Winchesters on the wall are real.',
                                        'whatToDo': [
                                                  'Grab a seat at the bar or a table — order from the Gannett Grill menu',
                                                  'Try a Lander Brewing Co. beer on tap — brewed in a glass-walled nano-brewery visible from the Cowfish restaurant next door',
                                                  'Look up at the original pressed-tin ceiling — it was hidden behind beadboard for decades until the owners renovated',
                                                  'Check the walls: trophy elk antlers, Winchester rifles, a zebra head in a cowboy hat, and a 1930s photo of Lander',
                                        ],
                                        'proTips': [
                                                  'The Coalter Block is actually five businesses in one complex: the Bar, Gannett Grill, Cowfish, Scream Shack, and Lander Brewing',
                                                  'Burgers and hand-tossed sourdough pizza are the Gannett Grill signatures',
                                                  'This building was also briefly a boarding house — the rooms upstairs are now an event space called The Loft',
                                        ],
                                        'context': "The Coalter House was built in 1907 on Lander's Main Street. Over the decades it cycled through identities — saloon, hotel, brothel, boarding house, dive bar — before three partners bought and renovated it, exposing the tin ceilings and filling it with Western artifacts. The Lander Brewing Company is a satellite of Snake River Brewery, reviving a brand that originally operated in the late 1800s before Prohibition shut it down.",
                                        'latitude': 42.8325,
                                        'longitude': -108.7276,
                                        'type': 'food',
                                        'estimatedDurationMinutes': 45,
                                        'arrivalRadiusMeters': 220,
                                        'suggestedDuration': '40–50 min',
                                        'costNote': '~$15–25/person for lunch + beer',
                                        'hoursToday': '11:00 AM – 2:00 AM',
                                        'whatToOrder': 'Burger or sourdough pizza from Gannett Grill, with a Lander Brewing beer on tap.',
                                        'photoTips': 'The tin ceiling from the bar, and the zebra head wearing a cowboy hat.',
                                        'parkingNotes': 'Street parking on Main St.',
                              },
                              {
                                        'id': 'sinks-canyon',
                                        'name': 'Sinks Canyon State Park',
                                        'subtitle': 'The Disappearing River',
                                        'revealEmoji': '🌊',
                                        'hook': 'A river that plunges into a cave, vanishes underground, and reappears a quarter mile away — with MORE water than went in. Scientists dye-tested it. It takes over two hours to travel a quarter mile. Nobody can explain the extra water.',
                                        'whatToDo': [
                                                  'Drive to the Sinks overlook first (signed from the road) — watch the Popo Agie River pour into the limestone cavern and disappear',
                                                  'Then drive 0.3 mi down the road to the Rise parking area',
                                                  'Walk to the Rise overlook — the river reappears here in a calm, clear pool',
                                                  'Feed the trout: coin-operated fish food machine at the Rise (bring quarters). The giant trout go absolutely berserk when food hits the water',
                                                  'If time allows, walk the short trail connecting the Sinks to the Rise along the surface above the underground river',
                                        ],
                                        'proTips': [
                                                  "The fish at the Rise are 8–12 pound rainbow trout. They've been protected from fishing since 1919 and they know it",
                                                  "More water comes out at the Rise than goes into the Sinks. The leading theory is the underground river picks up additional subsurface water, but it's never been proven",
                                                  "The name 'Popo Agie' comes from the Crow language — pronounced po-PO-zhuh — meaning 'gurgling river'",
                                                  "This is Wyoming's first certified International Dark Sky Place, if you're ever here at night",
                                        ],
                                        'context': "Sinks Canyon has been a geological curiosity since the area was first settled. Geologists have studied the underground passage for decades. Dye injected at the Sinks takes over two hours to appear at the Rise, despite the quarter-mile distance — suggesting a complex, winding route through the Madison Limestone formation carved by ancient glacial movement. The state park was created in 1971, the first park under Wyoming's newly formed Recreation Commission.",
                                        'latitude': 42.747,
                                        'longitude': -108.8132,
                                        'type': 'nature',
                                        'estimatedDurationMinutes': 30,
                                        'arrivalRadiusMeters': 220,
                                        'suggestedDuration': '20–30 min',
                                        'costNote': 'Free. Bring quarters for the fish food machine.',
                                        'hoursToday': 'Grounds open dawn to dusk',
                                        'photoTips': "The Sinks cavern entrance is dramatic from the overlook. At the Rise, photograph the trout feeding frenzy — the fish are so large they're hard to believe.",
                                        'parkingNotes': 'Two separate small lots: one at the Sinks, one at the Rise. Both signed from the road.',
                                        'safetyNotes': 'Canyon road may be icy in early April. The overlook railings are sturdy but watch your footing near the Sinks — mist can make rocks slippery.',
                              },
                              {
                                        'id': 'wind-river-heritage-center',
                                        'name': 'Wind River Heritage Center',
                                        'subtitle': "A Trapper's Life Work",
                                        'revealEmoji': '🦬',
                                        'hook': 'Sixty-two animals mounted by a single man — a Wyoming trapper named Jake Korell who lived to 99 and did every piece of work himself. Then, in the next room, wax figures of the Old West including the autopsy of a man whose skin was made into shoes.',
                                        'whatToDo': [
                                                  'Ask for a guided tour — the guides are excellent and bring the mounts and wax figures to life with stories',
                                                  'Start with the taxidermy gallery: 62 full-body Wyoming wildlife mounts in naturalistic poses, plus 20+ head mounts',
                                                  'Move to the wax museum: 27+ life-size figures depicting Wyoming history — Lewis & Clark, Jim Bridger, Cattle Kate, and the notorious Big Nose George Parrot',
                                                  'Check out the trap collection and the 1908 wilderness cabin reconstruction',
                                        ],
                                        'proTips': [
                                                  "Jake Korell was a real working trapper — not a hobbyist. He donated his life's work for permanent display and was on-site answering questions until he passed at 99 in 2013",
                                                  'The Big Nose George Parrot diorama depicts his autopsy — his skin was tanned and made into a pair of shoes and a medicine bag. The shoes are real and are in a museum in Rawlins, Wyoming',
                                                  'The wax figures were originally a Jackson Hole tourist attraction, then moved to Thermopolis, then rescued and brought here when that closed in 2009',
                                        ],
                                        'context': "The Heritage Center combines two separate collections under one roof. Jake Korell's taxidermy represents a lifetime of trapping in Wyoming — all 62 mounts are native species, displayed in naturalistic poses that reflect a craftsman's deep understanding of the animals. The wax museum arrived via a more circuitous route, having been an attraction in Jackson Hole, then Thermopolis, before finding its current home in Riverton. The center is privately run and relies on visitor support to stay open.",
                                        'latitude': 43.025,
                                        'longitude': -108.38,
                                        'type': 'history',
                                        'estimatedDurationMinutes': 30,
                                        'arrivalRadiusMeters': 220,
                                        'suggestedDuration': '30–45 min',
                                        'costNote': '~$5/person',
                                        'hoursToday': '9:00 AM – 4:00 PM',
                                        'photoTips': 'The Jim Bridger wax figure is the signature piece. The Big Nose George scene is morbidly photogenic.',
                                        'parkingNotes': 'Lot in front on S Federal Blvd.',
                              },
                              {
                                        'id': 'wind-river-canyon',
                                        'name': 'Wind River Canyon',
                                        'subtitle': 'Two Billion Years in Twenty Miles',
                                        'revealEmoji': '🏔️',
                                        'hook': "You're about to drive through two and a half billion years of Earth's history. The canyon walls on either side are a cross-section of deep time — the oldest rocks at the top, the youngest at the bottom. Signs along the road name each era as you pass through it.",
                                        'whatToDo': [
                                                  'Drive slowly — this is the stop. The canyon IS the attraction.',
                                                  'Watch for interpretive signs along the road marking each geological era. The oldest rocks (Precambrian, 2.5 billion years) are at the north end near Thermopolis',
                                                  'Pull off at any of the marked pull-outs for photos — the canyon walls tower hundreds of feet above the road',
                                                  'Look for bighorn sheep on the cliff faces, especially on sunny ledges',
                                                  'The Bighorn River runs alongside the road the entire way — watch for fishermen in waders',
                                        ],
                                        'proTips': [
                                                  "The geological sequence here is inverted from what you'd expect — oldest rocks on TOP, youngest on the BOTTOM. This is because the canyon cuts through an anticline (an upward fold in the rock layers)",
                                                  'Late afternoon light is ideal — the canyon walls glow amber and red',
                                                  'This is the same river that was called the Wind River upstream (south of the canyon) and becomes the Bighorn River downstream (north). Same river, two names. The canyon is where the name changes.',
                                        ],
                                        'context': 'Wind River Canyon is a 20-mile gorge carved by the river through the Owl Creek Mountains. The exposed rock layers span from the Precambrian era (2.5 billion years ago) to the Cretaceous period (65 million years ago), making it one of the most complete visible geological records accessible by car in North America. The highway and a railroad track share the narrow canyon floor with the river.',
                                        'latitude': 43.38,
                                        'longitude': -108.18,
                                        'type': 'scenic',
                                        'estimatedDurationMinutes': 40,
                                        'arrivalRadiusMeters': 220,
                                        'suggestedDuration': '30–45 min (driving through, with stops for photos)',
                                        'costNote': 'Free',
                                        'hoursToday': 'Always accessible',
                                        'photoTips': 'The pull-outs at the narrows midway through are the most dramatic. Shoot upward with a person for scale. The Bighorn River reflections work well in calm sections.',
                                        'parkingNotes': 'Multiple signed pull-outs along the 20-mile route. All are right off the highway.',
                                        'safetyNotes': 'Stay in pull-outs for photos — the road is two-lane with limited shoulder. Watch for trucks.',
                              },
                              {
                                        'id': 'safari-club-lounge',
                                        'name': 'Safari Club Lounge',
                                        'subtitle': 'Inside the Days Inn',
                                        'revealEmoji': '🦌',
                                        'hook': "Walk into a Wyoming Days Inn. Find a world-class taxidermy collection from six continents covering every wall, ceiling, and surface. A looming bear greets you at the entrance. They'll hand you a diagram of the walls.",
                                        'whatToDo': [
                                                  'Enter the Days Inn lobby — the taxidermy starts immediately',
                                                  'Ask at the bar or front desk for the wall diagram — it maps every mount by species and origin',
                                                  'Work through the rooms: lobby, restaurant, bar, and the hallway connecting to the hotel. Every surface is covered',
                                                  'Look for the specimens from Mongolia and Tajikistan — the most unusual pieces in the collection',
                                                  'Grab a beer at the bar if you want to sit and take it in',
                                        ],
                                        'proTips': [
                                                  'About 85% of the collection was hunted by one man — Jim Mills, who owned the hotel since 1978. He hunted on every continent except Antarctica',
                                                  "Mills passed away in 2022. The collection's future is uncertain — the family is looking for a permanent home. See it while you can.",
                                                  'Skip the food — reviews are mixed on quality. The bar drinks and the taxidermy are the real draw.',
                                                  'Watch the bird feeders outside the sun room windows — local deer raid them at night, and birds fight over them during the day',
                                        ],
                                        'context': "Jim Mills built the Safari Club restaurant onto his hotel in the early 1980s and filled it with trophies from a lifetime of hunting around the world. 'Someone once asked me, what do you do at the Holiday Inn?' Mills said. 'I keep the walls filled.' Many specimens are species now endangered or functionally extinct in the wild, making the collection both a trophy display and an unintentional time capsule of global wildlife.",
                                        'latitude': 43.65,
                                        'longitude': -108.21,
                                        'type': 'kitsch',
                                        'estimatedDurationMinutes': 20,
                                        'arrivalRadiusMeters': 220,
                                        'suggestedDuration': '15–20 min',
                                        'costNote': 'Free to browse. Beer ~$5–7.',
                                        'hoursToday': 'Bar open afternoons — verify at front desk',
                                        'whatToOrder': "A beer at the bar, if anything. Skip the food — you're eating at the Irma in Cody tonight.",
                                        'photoTips': 'The entrance bear is the money shot. The bar with mounts overhead is great for atmosphere.',
                                        'parkingNotes': 'Days Inn lot. Free.',
                              },
                              {
                                        'id': 'hot-springs-state-park',
                                        'name': 'Hot Springs State Park',
                                        'subtitle': "Wyoming's First State Park",
                                        'revealEmoji': '♨️',
                                        'hook': "Rainbow-colored mineral terraces built by the world's largest hot springs, flowing right into the Bighorn River. A herd of bison grazes in the park. A suspension bridge sways over the canyon.",
                                        'whatToDo': [
                                                  'Walk to the mineral terraces — the colors shift from white to orange to deep red depending on mineral concentration and water flow',
                                                  'Cross the Swinging Bridge over the Bighorn River for a view of the terraces from above',
                                                  'Look for the bison herd — about 15 animals graze in a fenced pasture within the park',
                                        ],
                                        'proTips': [
                                                  'The Shoshone and Arapaho tribes sold the hot springs to the U.S. in 1896 with a single condition: they must remain free to the public forever. That treaty is still honored today.',
                                                  'Over 8,000 gallons of 135-degree water flow over the terraces every 24 hours',
                                                  'The terraces are travertine — calcium carbonate deposited by the mineral water as it cools',
                                        ],
                                        'context': "Established in 1897, Hot Springs State Park is Wyoming's oldest state park. The land was purchased from the Eastern Shoshone, who had used the healing waters for generations. Chief Washakie of the Shoshone once built a personal bathhouse here. The park includes a free public bathhouse, commercial pools, and the Pioneer Home — a state-run assisted living facility that takes advantage of the therapeutic waters.",
                                        'latitude': 43.6511,
                                        'longitude': -108.2058,
                                        'type': 'nature',
                                        'estimatedDurationMinutes': 15,
                                        'arrivalRadiusMeters': 220,
                                        'suggestedDuration': '15 min',
                                        'costNote': 'Free',
                                        'hoursToday': 'Park always accessible',
                                        'photoTips': 'The terraces are most colorful when wet and in direct light. The Swinging Bridge makes a good foreground for a wide shot.',
                                        'parkingNotes': 'Park lots along the main road. Free.',
                                        'safetyNotes': 'Stay on designated paths near the terraces — the mineral crust can be fragile and the water underneath is scalding (135°F).',
                              },
                              {
                                        'id': 'meeteetse',
                                        'name': 'Meeteetse',
                                        'subtitle': 'Population 330',
                                        'revealEmoji': '🐾',
                                        'hook': "A ranching town so small it shouldn't be on the map — except this is where scientists rediscovered the black-footed ferret, the most endangered mammal in North America, after it was believed to be extinct.",
                                        'whatToDo': [
                                                  'Slow down through town and take in the main street — this is authentic small-town Wyoming',
                                                  'If you have 20 minutes, the Meeteetse Museums are on the main drag (local history + 1920s ranch photography)',
                                        ],
                                        'proTips': [
                                                  'In 1981, a ranch dog near Meeteetse brought home a dead animal nobody recognized. It turned out to be a black-footed ferret — a species the world had given up for extinct. The small population found here became the basis for every captive breeding program since.',
                                        ],
                                        'context': "Meeteetse sits where the Greybull River meets the Wood River in the Absaroka foothills. It's been a ranching town since the 1880s.",
                                        'latitude': 44.157,
                                        'longitude': -108.866,
                                        'type': 'history',
                                        'estimatedDurationMinutes': 5,
                                        'arrivalRadiusMeters': 180,
                                        'suggestedDuration': '5 min (drive-through)',
                                        'costNote': 'Free',
                                        'hoursToday': 'N/A — drive-through',
                              },
                              {
                                        'id': 'irma-hotel',
                                        'name': 'Irma Hotel',
                                        'subtitle': "Buffalo Bill's Place",
                                        'revealEmoji': '🤠',
                                        'hook': "Buffalo Bill Cody built this hotel in 1902 and named it after his daughter. The cherrywood bar inside was reportedly a gift from Queen Victoria. You're eating dinner where gunslingers and cattle barons drank.",
                                        'whatToDo': [
                                                  'Walk through the lobby first — check the original cash register, historical photos, and the ornate woodwork',
                                                  'Find the cherrywood back bar in the main dining room. Look at the carved detail — this was allegedly made in France and shipped to Cody as a gift from Queen Victoria.',
                                                  'Grab a table and order dinner',
                                                  "After eating, walk the hallway displays — guns, photos of Buffalo Bill's Wild West show, and family portraits",
                                        ],
                                        'proTips': [
                                                  "The food is decent but not exceptional — you're here for the atmosphere, not the cuisine. Stick to simple dishes: burgers, steaks, prime rib.",
                                                  'The hotel is still operating — you can stay the night if you want the full experience',
                                                  "In summer, there's a reenacted shootout on the street out front every evening. Not running in April, but the hotel feels like the Old West regardless.",
                                        ],
                                        'context': "Colonel William F. 'Buffalo Bill' Cody co-founded the town of Cody in 1896 and built the Irma Hotel in 1902 as its social centerpiece. He named it for his youngest daughter, Irma. The hotel anchored Cody's main street and served as a gathering point for ranchers, hunters, and tourists heading to Yellowstone. The building has operated continuously as a hotel for over 120 years.",
                                        'latitude': 44.5258,
                                        'longitude': -109.0644,
                                        'type': 'food',
                                        'estimatedDurationMinutes': 75,
                                        'arrivalRadiusMeters': 220,
                                        'suggestedDuration': '60–75 min',
                                        'costNote': '~$20–30/person for dinner',
                                        'hoursToday': 'Restaurant open for dinner (verify hours)',
                                        'whatToOrder': "Prime rib if it's on the special. Otherwise stick to burgers or steaks. Skip anything too ambitious.",
                                        'photoTips': 'The cherrywood back bar is the iconic shot. The exterior at dusk with the Sheridan Ave streetlights is also good.',
                                        'parkingNotes': 'Street parking on Sheridan Ave or side streets. Free in the evening.',
                              },
                    ],
          },
          {
                    'id': 'billings-day4',
                    'label': 'Cody → Hyrum',
                    'stops': [
                              {
                                        'id': 'nmmv-dubois',
                                        'name': 'National Museum of Military Vehicles',
                                        'subtitle': 'Smithsonian-Caliber in a Town of 900',
                                        'revealEmoji': '🪖',
                                        'hook': "A 160,000-square-foot military museum in a Wyoming town of 900 people. Over 500 restored vehicles. The musket that fired the first shot at Bunker Hill. General Patton's personal sidearm. Nobody expects this here. That's the point.",
                                        'whatToDo': [
                                                  'Plan for at least 2 hours — many visitors say they wished they had more time',
                                                  'The galleries are chronological: WWI → WWII → Korea → Vietnam → modern conflicts. Walk them in order for the full narrative arc',
                                                  "Don't miss the weapons vault — includes the musket from Bunker Hill, Patton's .45, and the complete Winchester collection from 1866 to 1966",
                                                  'Find the Higgins Boat — one of only 20 known surviving examples of the landing craft that delivered soldiers to the beaches on D-Day',
                                                  "The WWII gallery has battlefield soundscapes and immersive lighting — give it time, don't rush",
                                                  "Grab lunch at the Canteen next door (open 11am–3pm) if you're there over the midday",
                                        ],
                                        'proTips': [
                                                  'This started because one man (Dan Starks) wanted to drive a tank in the Dubois 4th of July parade. He bought a Sherman, then another, then it escalated to over 500 vehicles and a $40M museum.',
                                                  "Arriving right at opening (9:30) means you'll likely have the galleries almost to yourself for the first hour",
                                                  'The museum runs the Wilderness Healing Project, offering outdoor therapy to veterans — 100% of donations go directly to veteran services',
                                                  'Guided tours are available and highly recommended — the guides are often veterans themselves',
                                        ],
                                        'context': "The National Museum of Military Vehicles opened in 2020, built by Dan and Cynthia Starks on their ranch outside Dubois. What began as a personal collection of restored vehicles evolved into one of the most comprehensive military history museums in the country. The 160,000-square-foot facility houses the world's largest private collection of U.S. military ground vehicles on public display, alongside rare firearms, original D-Day invasion plans, and personal artifacts that tell the human stories behind the machinery.",
                                        'latitude': 43.4724,
                                        'longitude': -109.4958,
                                        'type': 'history',
                                        'estimatedDurationMinutes': 150,
                                        'arrivalRadiusMeters': 220,
                                        'suggestedDuration': '2–3 hours',
                                        'costNote': '$23/adult, $18 veterans, active military free',
                                        'hoursToday': '9:30 AM – 5:00 PM',
                                        'whatToOrder': 'The Canteen serves sandwiches and lunch fare 11am–3pm. Solid option — saves you from needing a separate lunch stop.',
                                        'photoTips': 'The Sherman tank in the entry atrium. The Higgins Boat. The weapons vault display cases. Ask before using flash on documents.',
                                        'parkingNotes': 'Large lot. Free.',
                              },
                              {
                                        'id': 'dubois-jackalope',
                                        'name': 'Giant Jackalope & Sasquatch-Unicorn Statue',
                                        'subtitle': 'Peak Wyoming',
                                        'revealEmoji': '🐰',
                                        'hook': 'A saddled jackalope you can ride inside a gas station. A fiberglass jackalope outside. A disco ball jackalope in a display case. And across the street, a metal-scrap Sasquatch leading a unicorn with a jackalope riding on its back. This is not a fever dream. This is Dubois.',
                                        'whatToDo': [
                                                  "Head inside the Exxon Country Store and find the big furry jackalope with the saddle — there's a step stool for mounting, a cowboy hat, and a lariat for props",
                                                  "Check the 'World's Largest Jackalope Exhibit' display case near the counter — includes the rare disco ball jackalope",
                                                  'Snap a photo with the fiberglass jackalope outside by the gas pumps',
                                                  'Walk across to see the Sasquatch-Unicorn-Jackalope metal sculpture on the main drag',
                                        ],
                                        'proTips': [
                                                  "Wyoming declared the Jackalope its 'Official Mythical Creature' in 2005. This is state-sanctioned cryptozoology.",
                                                  'The store has a solid selection of chocolates and Wyoming souvenirs beyond the jackalope kitsch',
                                                  'Good gas and bathroom stop too — the facilities are clean',
                                        ],
                                        'context': "The jackalope — a jackrabbit with antelope horns — is Wyoming's signature piece of folklore, originally popularized by Douglas, Wyoming, in the 1930s. Dubois has claimed its own piece of the legend with this gas station attraction, which has been delighting (and confusing) travelers for decades. The Sasquatch-Unicorn sculpture across the street appeared more recently and has no formal explanation, which feels appropriate.",
                                        'latitude': 43.5342,
                                        'longitude': -109.6374,
                                        'type': 'kitsch',
                                        'estimatedDurationMinutes': 10,
                                        'arrivalRadiusMeters': 180,
                                        'suggestedDuration': '10 min',
                                        'costNote': 'Free',
                                        'hoursToday': '7:00 AM – 8:00 PM',
                                        'photoTips': 'Sit on the indoor jackalope with the full cowboy hat and lariat setup. The outdoor fiberglass one works for a quick drive-by shot. The Sasquatch sculpture is best from across the street for full scale.',
                                        'parkingNotes': 'Gas station lot.',
                              },
                              {
                                        'id': 'continental-divide-togwotee',
                                        'name': 'Continental Divide',
                                        'subtitle': 'Togwotee Pass — 9,655 Feet',
                                        'revealEmoji': '⛰️',
                                        'hook': "You're standing on the spine of North America. Rain that falls to your left reaches the Atlantic. Rain that falls to your right reaches the Pacific. The pass is named for Togwotee, a Sheepeater Shoshone subchief who led the first recorded expedition over it in 1873.",
                                        'whatToDo': [
                                                  'Pull into the summit pull-off and find the Continental Divide sign',
                                                  "Take a photo — you're at 9,655 feet on the backbone of the continent",
                                                  'Look east: the volcanic Pinnacle Buttes and Breccia Cliffs you just drove through',
                                                  'Get back in the car and watch west — in a few miles, the Teton Range will appear in front of you all at once',
                                        ],
                                        'proTips': [
                                                  'The pronunciation is TOH-guh-tee, not TOG-wo-tee',
                                                  'The pass gets over 25 feet of snow annually — in early April there may still be snowpack on either side of the road',
                                                  "The Tetons are about to appear as you descend the west side. Don't blink — the reveal is sudden and enormous.",
                                        ],
                                        'context': "Togwotee Pass crosses the Continental Divide in the Absaroka Range at 9,655 feet. It's named for a Sheepeater Shoshone subchief who guided Captain William A. Jones and his military expedition over this route in 1873, though the pass had been an important trade route for native tribes long before. The pass sits between Two Ocean Mountain and Breccia Peak, surrounded by volcanic formations from ancient eruptions.",
                                        'latitude': 43.75,
                                        'longitude': -110.0833,
                                        'type': 'scenic',
                                        'estimatedDurationMinutes': 5,
                                        'arrivalRadiusMeters': 180,
                                        'suggestedDuration': '5 min',
                                        'costNote': 'Free',
                                        'hoursToday': 'Always accessible',
                                        'photoTips': "The Continental Divide sign with snow-covered peaks behind it. If it's clear, you can see in both directions from the summit pull-off.",
                                        'parkingNotes': 'Pull-off at the summit. Room for several vehicles.',
                                        'safetyNotes': "Road can close in severe storms. Check WYDOT conditions. It's 9,655 ft — dress warm for the photo stop, even if it was mild in the valley.",
                              },
                              {
                                        'id': 'oxbow-bend',
                                        'name': 'Oxbow Bend',
                                        'subtitle': 'The Reflection',
                                        'revealEmoji': '🫎',
                                        'hook': 'One of the most photographed spots in Grand Teton National Park. On a calm morning, Mt. Moran reflects perfectly in the still water of an old river meander. Moose, elk, pelicans, and beaver frequent the marshy banks.',
                                        'whatToDo': [
                                                  'Pull into the signed turnout on the east side of the highway',
                                                  'Walk to the overlook — Mt. Moran and the northern Tetons are directly across the water',
                                                  'Scan the marshy shoreline for wildlife — moose are frequently spotted here, especially in the willows',
                                                  'If the water is calm, the mountain reflection is the shot',
                                        ],
                                        'proTips': [
                                                  'This is better in early morning for reflections, but mid-afternoon still delivers strong views',
                                                  "The 'oxbow' is an old meander of the Snake River that was cut off as the river changed course — the slow, marshy water is what makes it such a wildlife magnet",
                                                  'Bring binoculars if you have them — pelicans, bald eagles, and great blue herons are all common here',
                                        ],
                                        'context': "Oxbow Bend is a slowly moving, semi-abandoned meander of the Snake River in the northern section of Grand Teton National Park. The pullout is one of the park's most popular viewpoints, offering a direct line of sight to Mt. Moran (12,605 ft) with its distinctive black dike and falling glacier. The calm water creates mirror-like reflections that have made this one of the most iconic landscape photography locations in the American West.",
                                        'latitude': 43.8553,
                                        'longitude': -110.5378,
                                        'type': 'scenic',
                                        'estimatedDurationMinutes': 5,
                                        'arrivalRadiusMeters': 180,
                                        'suggestedDuration': '5 min',
                                        'costNote': 'Free (GTNP pass $35/vehicle required)',
                                        'hoursToday': 'Always accessible',
                                        'photoTips': 'The reflection is best with calm water — wind destroys it. Even without a reflection, the mountain view is spectacular. Use a wide-angle to capture the full sweep.',
                                        'parkingNotes': 'Signed turnout. Can fill up in summer but should be easy in early April.',
                                        'safetyNotes': "You're in grizzly bear country. Stay in the turnout area. Do not approach wildlife.",
                              },
                              {
                                        'id': 'snake-river-overlook',
                                        'name': 'Snake River Overlook',
                                        'subtitle': 'The Ansel Adams Shot',
                                        'revealEmoji': '📸',
                                        'hook': "This is the viewpoint where Ansel Adams photographed one of the most famous landscape images in American history — the Teton Range rising above an S-curve in the Snake River. You're standing where he stood.",
                                        'whatToDo': [
                                                  'Pull into the signed overlook on the west side of the highway',
                                                  'Walk to the viewpoint — the entire Teton Range spreads out before you with the Snake River winding below',
                                                  "Compare the view to Adams' 1942 photograph — the composition is instantly recognizable",
                                                  'Scan the flats below for bison — herds are frequently visible in the sagebrush meadows',
                                        ],
                                        'proTips': [
                                                  'Adams shot his famous image in 1942 — the trees have grown significantly since then, partially obscuring the river bend. The view is still incredible but different from the original photo.',
                                                  'Fall is the classic season for this shot (golden cottonwoods), but the snow-capped spring Tetons against blue sky are arguably just as dramatic',
                                                  "There's a short trail to the right of the first pullout that leads to a slightly different angle — sometimes less crowded",
                                        ],
                                        'context': "Ansel Adams photographed 'The Tetons and the Snake River' from roughly this vantage point in 1942, creating one of the most reproduced landscape photographs in history. The image was later included on the Golden Record aboard the Voyager spacecraft as a representation of Earth's natural beauty. The National Park Service maintains the overlook as a designated viewpoint.",
                                        'latitude': 43.778,
                                        'longitude': -110.59,
                                        'type': 'scenic',
                                        'estimatedDurationMinutes': 5,
                                        'arrivalRadiusMeters': 180,
                                        'suggestedDuration': '5 min',
                                        'costNote': 'Free (GTNP pass required)',
                                        'hoursToday': 'Always accessible',
                                        'photoTips': 'Wide-angle to capture the full range + river curve. The Adams composition is roughly center-right of the overlook. Late afternoon light warms the peaks.',
                                        'parkingNotes': 'Signed pullout. Can be busy in summer but manageable in April.',
                                        'safetyNotes': 'Bear country. Stay near the overlook.',
                              },
                              {
                                        'id': 'moos-ice-cream-jackson',
                                        'name': "Moo's Gourmet Ice Cream",
                                        'subtitle': 'Best Dessert in Wyoming',
                                        'revealEmoji': '🫐',
                                        'hook': "The Food Network flew to Jackson to name this the best dessert in Wyoming. All organic cream. No preservatives. No artificial anything. The Wild Huckleberry is the one — made with berries that grow wild in the Rockies and can't be commercially farmed.",
                                        'whatToDo': [
                                                  "Find Moo's on the southeast corner of Jackson's Town Square — look for the green storefront",
                                                  'Order the Wild Huckleberry. This is the one. If you want a second flavor, Buzz Bomb (extreme espresso with chocolate shavings) is the runner-up.',
                                                  'Take your cone to the Town Square and get a photo under the elk antler arches — there are four arches, one at each corner of the square',
                                                  "People-watch on the square while you eat. Jackson's town square is one of the most recognizable public spaces in the West.",
                                        ],
                                        'proTips': [
                                                  "Wild huckleberries grow throughout the northern Rockies but can't be domesticated or commercially farmed — they only grow wild. That's why this flavor is specific to this region.",
                                                  'The scoops are generous but not Farson-absurd. A single is plenty. A twin cone lets you try two flavors.',
                                                  'The elk antler arches on the square are made from naturally shed antlers collected from the nearby National Elk Refuge every spring — no elk are harmed. Boy Scouts have been collecting them since the 1950s.',
                                        ],
                                        'context': "Moo's has been on Jackson's Town Square since 1996, making ice cream with organic cream from a natural dairy farm, pure cane sugar, and egg yolks. No preservatives, no colorings, no guar gum, no stabilizers. The Food Network named their Wild Huckleberry ice cream the best dessert in Wyoming during a 50-states challenge. Yelp and 24/7 Wall Street have both named it the best ice cream parlor in the state.",
                                        'latitude': 43.4799,
                                        'longitude': -110.7624,
                                        'type': 'food',
                                        'estimatedDurationMinutes': 20,
                                        'arrivalRadiusMeters': 220,
                                        'suggestedDuration': '15–20 min',
                                        'costNote': '~$7–10 per cone',
                                        'hoursToday': '12:30 PM – 9:00 PM',
                                        'whatToOrder': 'Wild Huckleberry in a waffle cone. Or a twin cone with Huckleberry and Buzz Bomb.',
                                        'photoTips': 'Cone + elk antler arch is the shot. The Town Square is also photogenic on its own — log-cabin style buildings with the Tetons visible above the rooflines on a clear day.',
                                        'parkingNotes': 'Street parking around the Town Square. 2-hour limit. April weekday should be easy.',
                              },
                              {
                                        'id': 'napoleon-dynamite-house',
                                        'name': "Napoleon Dynamite's House",
                                        'subtitle': 'Gosh!',
                                        'revealEmoji': '🦙',
                                        'hook': "This is the actual house from the movie. The one where Napoleon lived with Uncle Rico and Grandma. It's a real private residence in Preston, Idaho — and it looks exactly like you remember it.",
                                        'whatToDo': [
                                                  'Slow down on the north end of Preston — the house is visible from the road on the right',
                                                  'Quick photo from the car or the road shoulder',
                                                  "Do NOT go onto the property — it's a private residence and the owners live there",
                                        ],
                                        'proTips': [
                                                  'Napoleon Dynamite was filmed almost entirely in Preston, Idaho, in 2003 for a budget of $400,000. It grossed $46 million.',
                                                  "Preston is also home to the 'Napoleon Dynamite Festival' and several other filming locations around town — but on a drive-by, the house is the most recognizable",
                                                  'The llama (Tina) is not there. Sorry.',
                                        ],
                                        'context': "Napoleon Dynamite was written and directed by Jared Hess, a BYU film school student who grew up in Preston. The house, along with most of the film's locations, are real Preston buildings that Hess chose for their authenticity. The film became a cult classic and put Preston on the map as an unlikely tourist destination.",
                                        'latitude': 42.103,
                                        'longitude': -111.884,
                                        'type': 'kitsch',
                                        'estimatedDurationMinutes': 2,
                                        'arrivalRadiusMeters': 180,
                                        'suggestedDuration': '2 min',
                                        'costNote': 'Free',
                                        'hoursToday': 'Always visible from road',
                                        'photoTips': "From the road. The house is most recognizable from the front. Don't trespass.",
                                        'parkingNotes': 'Road shoulder. Quick stop.',
                                        'safetyNotes': "Private residence. View from road only. Don't be that person.",
                              },
                    ],
          },
],
    },
    {
      id: 'halls',
      name: 'The Halls',
      days: [
        {
          id: 'halls-test',
          label: 'Test Route — Drive Home',
          stops: [
            {
              id: 'halls-test-stop1',
              name: 'Home Sweet Home',
              subtitle: 'The final destination',
              revealEmoji: '🏠',
              hook: 'You made it. The reveal system works.',
              whatToDo: [
                'Check that the animation played in sequence.',
                'Try switching between tabs.',
                'Tap "Finish Trip" and verify the completion screen.',
              ],
              proTips: [
                'If you tapped during the animation, it should have snapped to complete.',
                'Try killing the app and relaunching to test resume.',
              ],
              context:
                'This is a test stop for verifying the full reveal flow before the Billings beta.',
              latitude: 40.2551,
              longitude: -111.631,
              type: 'rest',
              estimatedDurationMinutes: 5,
              arrivalRadiusMeters: 250,
              suggestedDuration: '5 min',
              costNote: 'Free',
              hoursToday: 'Always open',
              parkingNotes: 'Your driveway.',
            },
          ],
        },
        {
          id: 'halls-day1',
          label: 'Day 1: Provo → ???',
          stops: [
            {
              id: 'halls-day1-stop1',
              name: 'TBD Halls Stop 1',
              subtitle: 'TBD',
              revealEmoji: '📍',
              hook: 'TBD — hook goes here.',
              whatToDo: ['TBD — action steps go here.'],
              proTips: ['TBD — pro tips go here.'],
              context: 'TBD — context goes here.',
              latitude: 40.2338,
              longitude: -111.6585,
              type: 'activity',
              estimatedDurationMinutes: 25,
              arrivalRadiusMeters: 200,
              suggestedDuration: '25 min',
              costNote: 'TBD',
              hoursToday: 'TBD',
            },
          ],
        },
      ],
    },
  ],
};
